### ISSUE TITLE
Portfolio metadata

### ISSUE THREAD

**Issue by stufraser1** [OasisLMF/OpenDataTransform#35]
@OmegaDroid 
CSV file contains the fields we would like to see in the UI, to record portfolio metadata.
Some fields require user free text entry, some pull directly from the mapping file, and other are dropdown lists for user selection.
[ODTF portfolio metadata.csv](https://github.com/OasisLMF/OpenDataTransform/files/7734502/ODTF.portfolio.metadata.csv)

**Comment by OmegaDroid** [comment]
@stufraser1 @benhayes21 My plan here is to use something closer to json schema. We have used the json schema elsewhere for generating dynamic fields for the connections. From the example above we will have:

```
- perils:
    title: Perils
    type: string
    enum:
        - "Earthquake - Shake Only"
        - Fire Following
        - ...
- line_of_business:
    title: Line Of Business
    type: string
    enum:
        - Residential
        - Commercial
        - ...
name:
    title: Portfolio Name
    type: string
entity_company_book:
    title: Entity/Company/Book
    type: string
as_of_date:
    title: As-Of Date
    type: date
...
```
This allows us to order the fields in the UI by changing the order in the config as well as providing some extra type info (ie for dates and numbers)

Does this sound reasonable?
